### ISSUE TITLE
Cannot compile ASN files

### ISSUE THREAD

**Issue by anhtrung87vn** [aligungr/ue-ran-sim#51]
Hi ,

When I compile the ASN files at step 4.8, it failed with below issue. Could you let me know how to fix it?

Error	SystemError : File /tmp/asn16229926315433191916.xml not found. Check that /home/lnatrung/ue-ran-sim/ASNSDK-TCE-JAVA-COMP-PC-LINUX-BIN64/Compiler/bin/asnp is executable.		Line 0 Column 0

Thanks,
Trung.

**Comment by aligungr** [comment]
Hi @anhtrung87vn, I am currently working on this issue. We will stop using Marben's library soon, since it is commercial and somewhat hard to use. These steps will no longer be needed.

**Comment by anhtrung87vn** [comment]
Thank @aligungr,
In the meantime, could you send me compiled files?

**Comment by aligungr** [comment]
@anhtrung87vn Unfortunately I cannot share the compiled files since the tool is commercial. But the good news is that, we will stop using this library in a few days.

**Comment by anhtrung87vn** [comment]
Thank @aligungr , I got it. Looking forward to your new library

**Comment by aligungr** [comment]
@anhtrung87vn Now it's done and merged to master.

**Comment by anhtrung87vn** [comment]
Thank @aligungr
