### ISSUE TITLE
Failed to compile crypto

### ISSUE THREAD

**Issue by anhtrung87vn** [aligungr/ue-ran-sim#56]
Hi @aligungr ,

When I execute "mvn compile", there was an issue with crypto. Could you show me how to fix it?

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for tr.havelsan.ueransim:sctp:jar:1.0.8
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ tr.havelsan.ueransim:root:1.0.8, /home/lnatrung/ue-ran-sim/pom.xml, line 57, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for tr.havelsan.ueransim:utils:jar:1.0.8
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ tr.havelsan.ueransim:root:1.0.8, /home/lnatrung/ue-ran-sim/pom.xml, line 57, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for tr.havelsan.ueransim:core:jar:1.0.8
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ tr.havelsan.ueransim:root:1.0.8, /home/lnatrung/ue-ran-sim/pom.xml, line 57, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for tr.havelsan.ueransim:mts:jar:1.0.8
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ tr.havelsan.ueransim:root:1.0.8, /home/lnatrung/ue-ran-sim/pom.xml, line 57, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for tr.havelsan.ueransim:nas:jar:1.0.8
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ tr.havelsan.ueransim:root:1.0.8, /home/lnatrung/ue-ran-sim/pom.xml, line 57, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for tr.havelsan.ueransim:ngap:jar:1.0.8
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ tr.havelsan.ueransim:ngap:[unknown-version], /home/lnatrung/ue-ran-sim/ngap/pom.xml, line 14, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ tr.havelsan.ueransim:root:1.0.8, /home/lnatrung/ue-ran-sim/pom.xml, line 57, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for tr.havelsan.ueransim:control:jar:1.0.8
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ tr.havelsan.ueransim:root:1.0.8, /home/lnatrung/ue-ran-sim/pom.xml, line 57, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for tr.havelsan.ueransim:ueransim:jar:1.0.8
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ tr.havelsan.ueransim:root:1.0.8, /home/lnatrung/ue-ran-sim/pom.xml, line 57, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for tr.havelsan.ueransim:crypto:jar:1.0.8
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ tr.havelsan.ueransim:crypto:[unknown-version], /home/lnatrung/ue-ran-sim/crypto/pom.xml, line 24, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ tr.havelsan.ueransim:root:1.0.8, /home/lnatrung/ue-ran-sim/pom.xml, line 57, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for tr.havelsan.ueransim:root:pom:1.0.8
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 57, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] root
[INFO] core
[INFO] utils
[INFO] sctp
[INFO] mts
[INFO] crypto
[INFO] nas
[INFO] ngap
[INFO] control
[INFO] ueransim
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building root 1.0.8
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building core 1.0.8
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ core ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/lnatrung/ue-ran-sim/core/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ core ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 7 source files to /home/lnatrung/ue-ran-sim/core/target/classes
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building utils 1.0.8
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ utils ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/lnatrung/ue-ran-sim/utils/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ utils ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 38 source files to /home/lnatrung/ue-ran-sim/utils/target/classes
[INFO] /home/lnatrung/ue-ran-sim/utils/src/main/java/tr/havelsan/ueransim/utils/Utils.java: /home/lnatrung/ue-ran-sim/utils/src/main/java/tr/havelsan/ueransim/utils/Utils.java uses unchecked or unsafe operations.
[INFO] /home/lnatrung/ue-ran-sim/utils/src/main/java/tr/havelsan/ueransim/utils/Utils.java: Recompile with -Xlint:unchecked for details.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sctp 1.0.8
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sctp ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/lnatrung/ue-ran-sim/sctp/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ sctp ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 6 source files to /home/lnatrung/ue-ran-sim/sctp/target/classes
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building mts 1.0.8
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ mts ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/lnatrung/ue-ran-sim/mts/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ mts ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 10 source files to /home/lnatrung/ue-ran-sim/mts/target/classes
[INFO] /home/lnatrung/ue-ran-sim/mts/src/main/java/tr/havelsan/ueransim/mts/MtsConvert.java: Some input files use unchecked or unsafe operations.
[INFO] /home/lnatrung/ue-ran-sim/mts/src/main/java/tr/havelsan/ueransim/mts/MtsConvert.java: Recompile with -Xlint:unchecked for details.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building crypto 1.0.8
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:exec (crypto-native make command) @ crypto ---
rm -f *.o *.so
g++ -fPIC -c -I"/usr/lib/jvm/java-11-openjdk-amd64"/include -I"/usr/lib/jvm/java-11-openjdk-amd64"/include/linux -Wall -O2 -o tr_havelsan_ueransim_crypto_EIA3_128.o src/tr_havelsan_ueransim_crypto_EIA3_128.cpp
In file included from /usr/include/c++/5/cstdint:35:0,
                 from src/eia3_128.h:29,
                 from src/tr_havelsan_ueransim_crypto_EIA3_128.cpp:28:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
src/tr_havelsan_ueransim_crypto_EIA3_128.cpp:33:3: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
   auto IK = JniConvert::jbytearray_to_uint8array(pJniEnv, key, 1, nullptr);
   ^
In file included from src/tr_havelsan_ueransim_crypto_EIA3_128.cpp:28:0:
src/eia3_128.h:34:1: error: ‘uint32_t’ does not name a type
 uint32_t EIA3(uint8_t *pKey, uint32_t count, uint32_t direction, uint32_t bearer, uint32_t length, uint32_t *pData);
 ^
In file included from src/tr_havelsan_ueransim_crypto_EIA3_128.cpp:29:0:
src/jni_utils.h:36:1: error: ‘uint8_t’ does not name a type
 uint8_t *jbytearray_to_uint8array(JNIEnv *pJniEnv, jbyteArray pJba, jsize alignment, jsize *pOutLength);
 ^
src/jni_utils.h:38:1: error: ‘uint32_t’ does not name a type
 uint32_t *jbytearray_to_uint32array(JNIEnv *pJniEnv, jbyteArray pJba, jsize *pOutLength);
 ^
src/jni_utils.h:40:55: error: ‘uint32_t’ has not been declared
 jbyteArray uint32array_to_jbytearray(JNIEnv *pJniEnv, uint32_t *pArray, jsize nLength);
                                                       ^
src/jni_utils.h:42:52: error: ‘int32_t’ has not been declared
 jintArray int32array_to_jintarray(JNIEnv *pJniEnv, int32_t *pArray, jsize nLength);
                                                    ^
src/jni_utils.h:44:54: error: ‘uint8_t’ has not been declared
 jbyteArray uint8array_to_jbytearray(JNIEnv *pJniEnv, uint8_t *pArray, jsize nLength);
                                                      ^
src/tr_havelsan_ueransim_crypto_EIA3_128.cpp: In function ‘jint Java_tr_havelsan_ueransim_crypto_EIA3_1128_computeMac(JNIEnv*, jclass, jlong, jint, jboolean, jbyteArray, jint, jbyteArray)’:
src/tr_havelsan_ueransim_crypto_EIA3_128.cpp:33:3: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
   auto IK = JniConvert::jbytearray_to_uint8array(pJniEnv, key, 1, nullptr);
   ^
src/tr_havelsan_ueransim_crypto_EIA3_128.cpp:33:8: error: ‘IK’ does not name a type
   auto IK = JniConvert::jbytearray_to_uint8array(pJniEnv, key, 1, nullptr);
        ^
src/tr_havelsan_ueransim_crypto_EIA3_128.cpp:34:3: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
   auto M = JniConvert::jbytearray_to_uint32array(pJniEnv, message, nullptr);
   ^
src/tr_havelsan_ueransim_crypto_EIA3_128.cpp:34:8: error: ‘M’ does not name a type
   auto M = JniConvert::jbytearray_to_uint32array(pJniEnv, message, nullptr);
        ^
src/tr_havelsan_ueransim_crypto_EIA3_128.cpp:36:3: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
   auto MAC = EIA3_128::EIA3(IK, static_cast<uint32_t>(count), direction, static_cast<uint32_t>(bearer), static_cast<uint32_t>(bitLength), M);
   ^
src/tr_havelsan_ueransim_crypto_EIA3_128.cpp:36:8: error: ‘MAC’ does not name a type
   auto MAC = EIA3_128::EIA3(IK, static_cast<uint32_t>(count), direction, static_cast<uint32_t>(bearer), static_cast<uint32_t>(bitLength), M);
        ^
src/tr_havelsan_ueransim_crypto_EIA3_128.cpp:38:12: error: ‘IK’ was not declared in this scope
   delete[] IK;
            ^
src/tr_havelsan_ueransim_crypto_EIA3_128.cpp:39:12: error: ‘M’ was not declared in this scope
   delete[] M;
            ^
src/tr_havelsan_ueransim_crypto_EIA3_128.cpp:41:28: error: ‘MAC’ was not declared in this scope
   return static_cast<jint>(MAC);
                            ^
makefile:11: recipe for target 'tr_havelsan_ueransim_crypto_EIA3_128.o' failed
make: *** [tr_havelsan_ueransim_crypto_EIA3_128.o] Error 1
cp: cannot stat 'libcrypto-native.so': No such file or directory
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:982)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:929)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:457)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] root ............................................... SUCCESS [  0.093 s]
[INFO] core ............................................... SUCCESS [  2.421 s]
[INFO] utils .............................................. SUCCESS [  1.773 s]
[INFO] sctp ............................................... SUCCESS [  0.338 s]
[INFO] mts ................................................ SUCCESS [  0.788 s]
[INFO] crypto ............................................. FAILURE [  0.560 s]
[INFO] nas ................................................ SKIPPED
[INFO] ngap ............................................... SKIPPED
[INFO] control ............................................ SKIPPED
[INFO] ueransim ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.286 s
[INFO] Finished at: 2020-07-21T00:45:49-07:00
[INFO] Final Memory: 27M/100M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (crypto-native make command) on project crypto: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :crypto

Thanks,
Trung

**Comment by aligungr** [comment]
@anhtrung87vn Please make sure that you have the latest version of g++.

**Comment by anhtrung87vn** [comment]
Hi @aligungr ,

Yes, it is in the lastest version.

$sudo apt install g++
[sudo] password for lnatrung: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++ is already the newest version (4:5.3.1-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 187 not upgraded.

**Comment by aligungr** [comment]
Indeed 4:5.3 is an old version. In my computer I have g++ **version 7.5.0**
Please try following commands:

```
sudo apt update
sudo apt upgrade
sudo apt install g++
```

**Comment by anhtrung87vn** [comment]
Hi @aligungr ,

I update the g++ version to 7.5.0 but it still failed at crypto
Below is my installation step:

![image](https://user-images.githubusercontent.com/24509521/88080733-a7011900-cba9-11ea-9b87-8b72e9315f86.png)


Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/3.1.0/maven-shared-utils-3.1.0.jar (164 kB at 161 kB/s)
JAVA_HOME is not defined
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:982)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:929)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:457)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for root 1.0.8:
[INFO] 
[INFO] root ............................................... SUCCESS [  4.238 s]
[INFO] core ............................................... SUCCESS [01:32 min]
[INFO] utils .............................................. SUCCESS [  1.612 s]
[INFO] sctp ............................................... SUCCESS [  0.391 s]
[INFO] mts ................................................ SUCCESS [  0.780 s]
[INFO] crypto ............................................. FAILURE [ 12.853 s]
[INFO] nas ................................................ SKIPPED
[INFO] ngap ............................................... SKIPPED
[INFO] control ............................................ SKIPPED
[INFO] ueransim ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:52 min
[INFO] Finished at: 2020-07-21T23:19:27+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (crypto-native make command) on project crypto: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

**Comment by aligungr** [comment]
Hi @anhtrung87vn 
In this time the error message says: "JAVA_HOME is not defined"
Please set JAVA_HOME in your environment variables.

**Comment by anhtrung87vn** [comment]
Thank @aligungr,

It worked now, all were built successfully. do you have a guideline to use the tool?

**Comment by Iverson-Zheng** [comment]
> Thank @aligungr,
> 
> It worked now, all were built successfully. do you have a guideline to use the tool?

Hello, I meet the same problem like you. I tried to set the JAVA_HOME but failed.
Could you please give me some guidance or help to solve this problem?
Thank you very much!
