### ISSUE TITLE
How to run this useful simulator?

### ISSUE THREAD

**Issue by Iverson-Zheng** [aligungr/ue-ran-sim#63]
Thanks for  Shigeru Ishida's help, I have already built up this great simulator. But I still feel confused about using it.
According to the Readme.txt, this simulator is SA type and support 5G gNB & UE. In the corresponding yaml, I also found the configuration file.
By the way, would you mind telling me how to run this useful simulator? 
Thank you very much.

**Comment by s5uishida** [comment]
Place yaml/* (especially `gnb.yaml`) and `ueransim-1.0.8.jar` in the same directory and run as follows.
```
java -jar ueransim-1.0.8.jar
```
In addition, set the connection to AMF in `gnb.yaml` in advance.
I haven't succeeded in initial-registration yet, so please let me know if it has worked fine there.

**Comment by Iverson-Zheng** [comment]
> Place yaml/* (especially `gnb.yaml`) and `ueransim-1.0.8.jar` in the same directory and run as follows.
> 
> ```
> java -jar ueransim-1.0.8.jar
> ```
> 
> In addition, set the connection to AMF in `gnb.yaml` in advance.
> I haven't succeeded in initial-registration yet, so please let me know if it has worked fine there.

Sorry I can't find the file named ueransim-1.0.8.jar. Could you please tell me the directory of it?
Thanks a lot.

**Comment by aligungr** [comment]
@Iverson-Zheng the jar file is generated after "maven package" phase, and located at "ue-ran-sim/ueransim/target/ueransim-1.0.8.jar".

**Comment by Iverson-Zheng** [comment]
> Place yaml/* (especially `gnb.yaml`) and `ueransim-1.0.8.jar` in the same directory and run as follows.
> 
> ```
> java -jar ueransim-1.0.8.jar
> ```
> 
> In addition, set the connection to AMF in `gnb.yaml` in advance.
> I haven't succeeded in initial-registration yet, so please let me know if it has worked fine there.

Maybe I also failed in initial-registration, is the output log similar to your situation? 

Possible events:[
  "initial-registration"
]
Type event:
initial-registration
Event pushed.
Type event:
java.lang.NullPointerException
	at tr.havelsan.ueransim.sctp.SctpClient.send(SctpClient.java:75)
	at tr.havelsan.ueransim.api.gnb.GNodeB.sendToNetworkUeAssociated(GNodeB.java:109)
	at tr.havelsan.ueransim.api.gnb.GnbNasTransport.receiveUplinkNasTransport(GnbNasTransport.java:72)
	at tr.havelsan.ueransim.api.gnb.GNodeB.cycle(GNodeB.java:180)
	at tr.havelsan.ueransim.core.threads.NodeLooperThread.run(NodeLooperThread.java:50)

**Comment by Iverson-Zheng** [comment]
> @Iverson-Zheng the jar file is generated after "maven package" phase, and located at "ue-ran-sim/ueransim/target/ueransim-1.0.8.jar".

Hello @aligungr , Can I put this simulator on another PC which is different from Open5GS PC? 
I tried to change the host address in gNB.yaml but It failed with the following information. By the way, how to connect this simulator with another 5GC PC?

Type event:
java.lang.RuntimeException: java.net.ConnectException: Connection refused
	at tr.havelsan.ueransim.core.threads.SctpRecevierThread.run(SctpRecevierThread.java:52)
Caused by: java.net.ConnectException: Connection refused
	at jdk.sctp/sun.nio.ch.sctp.SctpNet.connect0(Native Method)
	at jdk.sctp/sun.nio.ch.sctp.SctpNet.connect(SctpNet.java:68)
	at jdk.sctp/sun.nio.ch.sctp.SctpChannelImpl.connect(SctpChannelImpl.java:378)
	at jdk.sctp/sun.nio.ch.sctp.SctpChannelImpl.connect(SctpChannelImpl.java:445)
	at jdk.sctp/com.sun.nio.sctp.SctpChannel.open(SctpChannel.java:226)
	at tr.havelsan.ueransim.sctp.SctpClient.start(SctpClient.java:63)
	at tr.havelsan.ueransim.core.threads.SctpRecevierThread.run(SctpRecevierThread.java:49)

**Comment by aligungr** [comment]
> > Place yaml/* (especially `gnb.yaml`) and `ueransim-1.0.8.jar` in the same directory and run as follows.
> > ```
> > java -jar ueransim-1.0.8.jar
> > ```
> > 
> > 
> > In addition, set the connection to AMF in `gnb.yaml` in advance.
> > I haven't succeeded in initial-registration yet, so please let me know if it has worked fine there.
> 
> Maybe I also failed in initial-registration, is the output log similar to your situation?
> 
> Possible events:[
> "initial-registration"
> ]
> Type event:
> initial-registration
> Event pushed.
> Type event:
> java.lang.NullPointerException
> at tr.havelsan.ueransim.sctp.SctpClient.send(SctpClient.java:75)
> at tr.havelsan.ueransim.api.gnb.GNodeB.sendToNetworkUeAssociated(GNodeB.java:109)
> at tr.havelsan.ueransim.api.gnb.GnbNasTransport.receiveUplinkNasTransport(GnbNasTransport.java:72)
> at tr.havelsan.ueransim.api.gnb.GNodeB.cycle(GNodeB.java:180)
> at tr.havelsan.ueransim.core.threads.NodeLooperThread.run(NodeLooperThread.java:50)

**Comment by aligungr** [comment]
> > Place yaml/* (especially `gnb.yaml`) and `ueransim-1.0.8.jar` in the same directory and run as follows.
> > ```
> > java -jar ueransim-1.0.8.jar
> > ```
> > 
> > 
> > In addition, set the connection to AMF in `gnb.yaml` in advance.
> > I haven't succeeded in initial-registration yet, so please let me know if it has worked fine there.
> 
> Maybe I also failed in initial-registration, is the output log similar to your situation?
> 
> Possible events:[
> "initial-registration"
> ]
> Type event:
> initial-registration
> Event pushed.
> Type event:
> java.lang.NullPointerException
> at tr.havelsan.ueransim.sctp.SctpClient.send(SctpClient.java:75)
> at tr.havelsan.ueransim.api.gnb.GNodeB.sendToNetworkUeAssociated(GNodeB.java:109)
> at tr.havelsan.ueransim.api.gnb.GnbNasTransport.receiveUplinkNasTransport(GnbNasTransport.java:72)
> at tr.havelsan.ueransim.api.gnb.GNodeB.cycle(GNodeB.java:180)
> at tr.havelsan.ueransim.core.threads.NodeLooperThread.run(NodeLooperThread.java:50)

@Iverson-Zheng The reason of this error is that, you are trying to start initial-registration before SCTP connection establishes with gNB and AMF. Please check app.log before sending initial-registration to see if the connection is established yet

**Comment by aligungr** [comment]
> > @Iverson-Zheng the jar file is generated after "maven package" phase, and located at "ue-ran-sim/ueransim/target/ueransim-1.0.8.jar".
> 
> Hello @aligungr , Can I put this simulator on another PC which is different from Open5GS PC?
> I tried to change the host address in gNB.yaml but It failed with the following information. By the way, how to connect this simulator with another 5GC PC?
> 
> Type event:
> java.lang.RuntimeException: java.net.ConnectException: Connection refused
> at tr.havelsan.ueransim.core.threads.SctpRecevierThread.run(SctpRecevierThread.java:52)
> Caused by: java.net.ConnectException: Connection refused
> at jdk.sctp/sun.nio.ch.sctp.SctpNet.connect0(Native Method)
> at jdk.sctp/sun.nio.ch.sctp.SctpNet.connect(SctpNet.java:68)
> at jdk.sctp/sun.nio.ch.sctp.SctpChannelImpl.connect(SctpChannelImpl.java:378)
> at jdk.sctp/sun.nio.ch.sctp.SctpChannelImpl.connect(SctpChannelImpl.java:445)
> at jdk.sctp/com.sun.nio.sctp.SctpChannel.open(SctpChannel.java:226)
> at tr.havelsan.ueransim.sctp.SctpClient.start(SctpClient.java:63)
> at tr.havelsan.ueransim.core.threads.SctpRecevierThread.run(SctpRecevierThread.java:49)

@Iverson-Zheng Yes, you can use the simulator anywhere you want, but the point is both machines should be able to communicate each other over SCTP connection. You should check this first. After you ensure that machines can see each other over SCTP, you can start using our simulator in the same way.
